config/routes.rb
Rails.application.routes.draw do
  resources :comentarios

  resources :qualificacoes

  resources :clientes

  resources :restaurantes 

end

app/models/restaurante.rb
class Restaurante < ActiveRecord::Base
    extend FriendlyId
    scope :active, -> {where(:active => true)}
    friendly_id :nome, use: [:slugged, :finders]
    
    
    validates_presence_of :nome, message: "deve ser preenchido"
    validates_presence_of :endereco, message: "deve ser preenchido"
    validates_presence_of :especialidade, message: "deve ser preenchido"

    validates_uniqueness_of :nome, message: "nome já cadastrado"
    validates_uniqueness_of :endereco, message: "endereço já cadastrado"
    
    validate :primeira_letra_deve_ser_maiuscula
    
    
    has_many :qualificacoes
    has_and_belongs_to_many :pratos
    
    has_many :comentarios, :as => :comentavel
 private
    def primeira_letra_deve_ser_maiuscula
      errors.add(:nome,
         "primeira letra deve ser maiúscula") unless nome =~ /[A-Z].*/
    end
    
    def self.search(search, page)
      paginate :per_page => 5, :page => page,
               :conditions => ['nome like ?', "%#{search}%"],
               :order => 'nome'
    end
    
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  respond_to :html, :xml, :json
 
  def index
   # @restaurantes = Restaurante.order :nome
   #@restaurantes = Restaurante.all
    #render "index"
   @restaurantes = Restaurante.all.paginate(:page => params[:page], :per_page => 5)
    respond_to do |format|
          format.html
          format.xml { render :xml => @restaurantes }
          format.json { render :json => @restaurantes }
    end
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
   
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
    #@restaurante = Restaurante.find(params[:id])
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)
    #@restaurante = Restaurante.new params.require(:restaurante).permit(:nome, :endereco,:especialidade)
    #@restaurante = Restaurante.new(params[:restaurante])
    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante criado com sucesso!.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
   # @restaurante = Restaurante.find params[:id]
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante editado  com sucesso!.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
   # @restaurante = Restaurante.find(params[:id])
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante deletado com sucesso!.' }
      format.json { head :no_content }
      
     # redirect_to action: 'index'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.friendly.find(params[:id])
    end
    
    def self.find_by_slug(slug)
      result = find(slug)
      if result.to_param == slug
        result
      else
        raise ActiveRecord::RecordNotFound
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:nome, :endereco, :especialidade)
      #params[:restaurante]
    end
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_form.html.erb
<%= form_for(@restaurante) do |f| %>
  <% if @restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% @restaurante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @restaurante do |f| %>
    Nome: <%= f.text_field :nome %><br/>
    Endereço: <%= f.text_field :endereco %><br/>
    Especialidade: <%= f.text_field :especialidade %><br/>
    <%= f.submit %>
  <% end %>

  
<% end %>

app/views/restaurantes/edit.html.erb
<h1>Editing restaurante</h1>
<% if @restaurante.errors.any? %>
<ul>
<% @restaurante.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
<% end %>
</ul>
<%end%>

<%= form_for @restaurante do |f| %>
  Nome: <%= f.text_field :nome %><br/>
  Endereço: <%= f.text_field :endereco %><br/>
  Especialidade: <%= f.text_field :especialidade %><br/>
  <%= f.submit %>
<% end %>

<!--<%= render 'form' %>-->

<%= link_to 'Show', @restaurante %> |
<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/index.html.erb
<h1>Listing restaurantes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereço</th>
      <th>Especialidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= restaurante.nome          %></td>
        <td><%= restaurante.endereco      %></td>
        <td><%= restaurante.especialidade %></td>
         <td><%= link_to 'Show', restaurante %></td>
        <td><%= link_to 'Edit', edit_restaurante_path(restaurante) %></td>
        <td><%= link_to 'Destroy', restaurante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>
<%= will_paginate @restaurantes %>
<br>

<%= link_to 'New Restaurante', new_restaurante_path %>

app/views/restaurantes/new.html.erb
<h1>New restaurante</h1>
<%= render 'form' %>
<%= link_to 'Back', restaurantes_path %>

app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Exibindo Restaurante</h1>

<p><b>Nome:</b> <%= @restaurante.nome %></p>
<p><b>Endereço:</b> <%= @restaurante.endereco %></p>
<p><b>Especialidade:</b> <%= @restaurante.especialidade %></p>
<b>Nota média: </b><%= @restaurante.qualificacoes.average(:nota) %><br/>
<b>Qualificações: </b><%= @restaurante.qualificacoes.count %><br/>
<b>Preço médio: </b><%= @restaurante.qualificacoes.average(:valor_gasto) %><br/>
<p><%= comentarios @restaurante %></p>
<p><%= novo_comentario @restaurante %></p>

<%= link_to "Qualificar este restaurante", controller: "qualificacoes", action: "new", restaurante: @restaurante %>
<%= link_to 'Edit', edit_restaurante_path(@restaurante) %> |
<%= link_to 'Back', restaurantes_path %>